[project]
name = "semi-search"
version = "0.1.0"
description = "An understanding database engine"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "numpy>=2.3.4",
]

[dependency-groups]
dev = [
    "memory-profiler>=0.61.0",
]
